version: '2'
services:
    phosphpred-app:
        image: phosphpred
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://phosphpred-mysql:3306/phosphpred?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    phosphpred-mysql:
        extends:
            file: mysql.yml
            service: phosphpred-mysql
